/**
 * ResQMesh App Interface UI Dictionary across major Indian Languages
 * Enables complete offline UI localization for citizens.
 */
const localizedPhrases = {
  "en-IN": {
    app_title: "ResQMesh Citizen Safety",
    status_safe: "You are currently safe",
    status_alert: "Emergency Nearby",
    sos_button: "SOS - I NEED HELP",
    report_button: "Report Emergency",
    safe_zones_button: "Find Safe Zone",
    onboarding_step1_title: "Step 1 - Personal Information",
    onboarding_step2_title: "Step 2 - Medical Details",
    onboarding_step3_title: "Step 3 - Emergency Contact",
    full_name_label: "Full Name",
    age_label: "Age",
    blood_group_label: "Blood Group",
    allergies_label: "Allergies",
    medical_conditions_label: "Existing Medical Conditions",
    medications_label: "Current Medications",
    contact_name_label: "Contact Name",
    relationship_label: "Relationship",
    phone_label: "Phone Number",
    preferred_language_label: "Preferred Language",
    sos_modal_title: "Send Emergency SOS?",
    sos_category_medical: "Medical Emergency",
    sos_category_trapped: "Trapped / Stranded",
    sos_category_fire: "Fire Hazard",
    sos_category_injury: "Severe Injury",
    sos_category_other: "Other Emergency",
    sos_sending: "Transmitting SOS Request...",
    sos_sent_title: "SOS Sent",
    sos_sent_desc: "Your emergency request has been transmitted to rescuers.",
    logout_confirm_title: "Log Out & Start Again?",
    logout_confirm_desc: "Are you sure you want to log out? Your profile information will be cleared and setup restarted.",
    btn_confirm: "Yes, Log Out & Start Again",
    btn_cancel: "Cancel",
    btn_next: "Next",
    btn_complete: "Complete Setup"
  },
  "hi-IN": {
    app_title: "ResQMesh नागरिक सुरक्षा",
    status_safe: "आप वर्तमान में सुरक्षित हैं",
    status_alert: "पास में आपात स्थिति",
    sos_button: "SOS - मुझे सहायता चाहिए",
    report_button: "आपात स्थिति दर्ज करें",
    safe_zones_button: "सुरक्षित क्षेत्र खोजें",
    onboarding_step1_title: "चरण 1 - व्यक्तिगत जानकारी",
    onboarding_step2_title: "चरण 2 - चिकित्सा विवरण",
    onboarding_step3_title: "चरण 3 - आपातकालीन संपर्क",
    full_name_label: "पूरा नाम",
    age_label: "आयु",
    blood_group_label: "रक्त समूह (Blood Group)",
    allergies_label: "एलर्जी",
    medical_conditions_label: "मौजूदा बीमारियाँ",
    medications_label: "वर्तमान दवाएं",
    contact_name_label: "संपर्क नाम",
    relationship_label: "संबंध",
    phone_label: "फोन नंबर",
    preferred_language_label: "पसंदीदा भाषा",
    sos_modal_title: "आपातकालीन SOS भेजें?",
    sos_category_medical: "चिकित्सा आपातकाल",
    sos_category_trapped: "फंसा हुआ (Trapped)",
    sos_category_fire: "आग की घटना",
    sos_category_injury: "गंभीर चोट",
    sos_category_other: "अन्य आपात स्थिति",
    sos_sending: "SOS ट्रांसमिट हो रहा है...",
    sos_sent_title: "SOS भेज दिया गया है",
    sos_sent_desc: "आपका आपातकालीन अनुरोध बचाव दल तक पहुंचा दिया गया है।",
    logout_confirm_title: "लॉग आउट करें और पुनः प्रारंभ करें?",
    logout_confirm_desc: "क्या आप निश्चित हैं? आपकी प्रोफ़ाइल साफ़ हो जाएगी और सेटअप पुनः शुरू होगा।",
    btn_confirm: "हां, रीसेट करें",
    btn_cancel: "रद्द करें",
    btn_next: "आगे बढ़ें",
    btn_complete: "सेटअप पूरा करें"
  },
  "ta-IN": {
    app_title: "ResQMesh குடிமக்கள் பாதுகாப்பு",
    status_safe: "நீங்கள் பாதுகாப்பாக உள்ளீர்கள்",
    status_alert: "அருகில் அவசரநிலை",
    sos_button: "SOS - எனக்கு உதவி வேண்டும்",
    report_button: "அவசரநிலையை புகாரளி",
    safe_zones_button: "பாதுகாப்பான மண்டலத்தை கண்டறி",
    onboarding_step1_title: "படி 1 - தனிப்பட்ட தகவல்கள்",
    onboarding_step2_title: "படி 2 - மருத்துவ விவரங்கள்",
    onboarding_step3_title: "படி 3 - அவசர தொடர்பு",
    full_name_label: "முழு பெயர்",
    age_label: "வயது",
    blood_group_label: "இரத்த வகை",
    allergies_label: "ஒவ்வாமைகள் (Allergies)",
    medical_conditions_label: "மருத்துவ நிலைகள்",
    medications_label: "தற்போதைய மருந்துகள்",
    contact_name_label: "தொடர்பு பெயர்",
    relationship_label: "உறவு",
    phone_label: "தொலைபேசி எண்",
    preferred_language_label: "விருப்ப மொழி",
    sos_modal_title: "SOS அனுப்பவா?",
    sos_category_medical: "மருத்துவ அவசரநிலை",
    sos_category_trapped: "சிக்கிக்கொண்டேன்",
    sos_category_fire: "தீ விபத்து",
    sos_category_injury: "கடும் காயம்",
    sos_category_other: "பிற அவசரநிலை",
    sos_sending: "SOS அனுப்பப்படுகிறது...",
    sos_sent_title: "SOS அனுப்பப்பட்டது",
    sos_sent_desc: "உங்கள் அவசர கோரிக்கை மீட்புக் குழுவிற்கு அனுப்பப்பட்டது.",
    logout_confirm_title: "வெளியேறி மீண்டும் தொடங்கவா?",
    logout_confirm_desc: "உங்கள் தகவல் அழிக்கப்பட்டு மீண்டும் அமைக்கப்படும்.",
    btn_confirm: "ஆம், மீட்டமைக்கவும்",
    btn_cancel: "ரத்து செய்",
    btn_next: "அடுத்து",
    btn_complete: "அமைப்பை முடி"
  },
  "te-IN": {
    app_title: "ResQMesh పౌర భద్రత",
    status_safe: "మీరు సురక్షితంగా ఉన్నారు",
    status_alert: "సమీపంలో అత్యవసర పరిస్థితి",
    sos_button: "SOS - నాకు సహాయం కావాలి",
    report_button: "అత్యవసర పరిస్థితిని నివేదించండి",
    safe_zones_button: "సురక్షిత ప్రాంతాన్ని కనుగొనండి",
    onboarding_step1_title: "దశ 1 - వ్యక్తిగత సమాచారం",
    onboarding_step2_title: "దశ 2 - వైద్య వివరాలు",
    onboarding_step3_title: "దశ 3 - అత్యవసర సంప్రదింపు",
    full_name_label: "పూర్తి పేరు",
    age_label: "వయస్సు",
    blood_group_label: "బ్లడ్ గ్రూప్",
    allergies_label: "అలర్జీలు",
    medical_conditions_label: "వైద్య ఆరోగ్య సమస్యలు",
    medications_label: "ప్రస్తుత మందులు",
    contact_name_label: "సంప్రదింపు పేరు",
    relationship_label: "సంబంధం",
    phone_label: "ఫోన్ నంబర్",
    preferred_language_label: "అభిరుచి గల భాష",
    sos_modal_title: "SOS పంపాలా?",
    sos_category_medical: "వైద్య అత్యవసర పరిస్థితి",
    sos_category_trapped: "చిక్కుకుపోయాను",
    sos_category_fire: "అగ్ని ప్రమాదం",
    sos_category_injury: "తీవ్రమైన గాయం",
    sos_category_other: "ఇతర అత్యవసర పరిస్థితి",
    sos_sending: "SOS పంపబడుతోంది...",
    sos_sent_title: "SOS పంపబడింది",
    sos_sent_desc: "మీ అత్యవసర విజ్ఞప్తి రక్షణ రక్షకులకు పంపబడింది.",
    logout_confirm_title: "లాగ్ అవుట్ చేసి మళ్లీ ప్రారంభించాలా?",
    logout_confirm_desc: "మీ సమాచారం తొలగించబడుతుంది.",
    btn_confirm: "అవును, రీసెట్ చేయండి",
    btn_cancel: "రద్దు చేయి",
    btn_next: "తరువాత",
    btn_complete: "పూర్తి చేయి"
  },
  "mr-IN": {
    app_title: "ResQMesh नागरिक सुरक्षा",
    status_safe: "तुम्ही सध्या सुरक्षित आहात",
    status_alert: "जवळपास आपत्कालीन परिस्थिती",
    sos_button: "SOS - मला मदतीची गरज आहे",
    report_button: "आपत्कालीन तक्रार नोंदवा",
    safe_zones_button: "सुरक्षित क्षेत्र शोधा",
    onboarding_step1_title: "पायरी १ - वैयक्तिक माहिती",
    onboarding_step2_title: "पायरी २ - वैद्यकीय तपशील",
    onboarding_step3_title: "पायरी ३ - आपत्कालीन संपर्क",
    full_name_label: "पूर्ण नाव",
    age_label: "वय",
    blood_group_label: "रक्तगट",
    allergies_label: "ॲलर्जी",
    medical_conditions_label: "वैद्यकीय आजार",
    medications_label: "सध्याची औषधे",
    contact_name_label: "संपर्क व्यक्तीचे नाव",
    relationship_label: "नाते",
    phone_label: "फोन नंबर",
    preferred_language_label: "पसंतीची भाषा",
    sos_modal_title: "SOS पाठवायचा?",
    sos_category_medical: "वैद्यकीय आणीबाणी",
    sos_category_trapped: "अडकलेला",
    sos_category_fire: "आग",
    sos_category_injury: "गंभीर दुखापत",
    sos_category_other: "इतर आणीबाणी",
    sos_sending: "SOS पाठवत आहे...",
    sos_sent_title: "SOS पाठवला",
    sos_sent_desc: "तुमची आपत्कालीन विनंती बचाव पथकाकडे पाठवली आहे.",
    logout_confirm_title: "लॉग आउट करून पुन्हा सुरू करायचे?",
    logout_confirm_desc: "आपली माहिती हटवली जाईल.",
    btn_confirm: "होय, रीसेट करा",
    btn_cancel: "रद्द करा",
    btn_next: "पुढे",
    btn_complete: "पूर्ण करा"
  },
  "bn-IN": {
    app_title: "ResQMesh নাগরিক সুরক্ষা",
    status_safe: "আপনি বর্তমানে নিরাপদ আছেন",
    status_alert: "কাছেই জরুরি অবস্থা",
    sos_button: "SOS - আমার সাহায্য প্রয়োজন",
    report_button: "জরুরি অবস্থা রিপোর্ট করুন",
    safe_zones_button: "নিরাপদ অঞ্চল খুঁজুন",
    onboarding_step1_title: "ধাপ ১ - ব্যক্তিগত তথ্য",
    onboarding_step2_title: "ধাপ ২ - চিকিৎসা সংক্রান্ত বিবরণ",
    onboarding_step3_title: "ধাপ ৩ - জরুরি যোগাযোগ",
    full_name_label: "সম্পূর্ণ নাম",
    age_label: "বয়স",
    blood_group_label: "রক্তের গ্রুপ",
    allergies_label: "অ্যালার্জি",
    medical_conditions_label: "বিদ্যমান শারীরিক অবস্থা",
    medications_label: "বর্তমান ওষুধ",
    contact_name_label: "যোগাযোগের নাম",
    relationship_label: "সম্পর্ক",
    phone_label: "ফোন নম্বর",
    preferred_language_label: "পছন্দের ভাষা",
    sos_modal_title: "জরুরি SOS পাঠাবেন?",
    sos_category_medical: "মেডিকেল জরুরি অবস্থা",
    sos_category_trapped: "আটকা পড়েছেন",
    sos_category_fire: "আগুন",
    sos_category_injury: "গুরুতর আঘাত",
    sos_category_other: "অন্যান্য জরুরি অবস্থা",
    sos_sending: "SOS পাঠানো হচ্ছে...",
    sos_sent_title: "SOS পাঠানো হয়েছে",
    sos_sent_desc: "আপনার অনুরোধ উদ্ধারকারী দলের কাছে পৌঁছে দেওয়া হয়েছে।",
    logout_confirm_title: "লগ আউট করে আবার শুরু করবেন?",
    logout_confirm_desc: "আপনার প্রোফাইল মুছে যাবে।",
    btn_confirm: "হ্যাঁ, রিসেট করুন",
    btn_cancel: "বাতিল করুন",
    btn_next: "পরবর্তী",
    btn_complete: "সম্পন্ন করুন"
  },
  "gu-IN": {
    app_title: "ResQMesh નાગરિક સુરક્ષા",
    status_safe: "તમે હાલમાં સુરક્ષિત છો",
    status_alert: "નજીકમાં કટોકટી",
    sos_button: "SOS - મને મદદ જોઈએ છે",
    report_button: "ઇમરજન્સી રિપોર્ટ કરો",
    safe_zones_button: "સુરક્ષિત ઝોન શોધો",
    onboarding_step1_title: "પગલું 1 - વ્યક્તિગત માહિતી",
    onboarding_step2_title: "પગલું 2 - તબીબી વિગતો",
    onboarding_step3_title: "પગલું 3 - ઇમરજન્સી સંપર્ક",
    full_name_label: "પૂરું નામ",
    age_label: "ઉંમર",
    blood_group_label: "બ્લડ ગ્રુપ",
    allergies_label: "એલર્જી",
    medical_conditions_label: "હાલની તબીબી સ્થિતિ",
    medications_label: "હાલની દવાઓ",
    contact_name_label: "સંપર્ક નામ",
    relationship_label: "સંબંધ",
    phone_label: "ફોન નંબર",
    preferred_language_label: "પસંદગીની ભાષા",
    sos_modal_title: "SOS મોકલવો?",
    sos_category_medical: "મેડિકલ ઇમરજન્સી",
    sos_category_trapped: "ફસાયેલા",
    sos_category_fire: "આગ",
    sos_category_injury: "ગંભીર ઈજા",
    sos_category_other: "અન્ય ઈમરજન્સી",
    sos_sending: "SOS મોકલાઈ રહ્યો છે...",
    sos_sent_title: "SOS મોકલાઈ ગયો",
    sos_sent_desc: "તમારી વિનંતી બચાવ ટીમ સુધી પહોંચાડી દેવામાં આવી છે.",
    logout_confirm_title: "લોગ આઉટ કરીને ફરીથી શરૂ કરવું?",
    logout_confirm_desc: "તમારી પ્રોફાઇલ સાફ થઈ જશે.",
    btn_confirm: "હા, રિસેટ કરો",
    btn_cancel: "રદ કરો",
    btn_next: "આગળ",
    btn_complete: "પૂર્ણ કરો"
  },
  "kn-IN": {
    app_title: "ResQMesh ನಾಗರಿಕ ಸುರಕ್ಷತೆ",
    status_safe: "ನೀವು ಪ್ರಸ್ತುತ ಸುರಕ್ಷಿತವಾಗಿದ್ದೀರಿ",
    status_alert: "ಸಮೀಪದಲ್ಲಿ ತುರ್ತು ಪರಿಸ್ಥಿತಿ",
    sos_button: "SOS - ನನಗೆ ಸಹಾಯ ಬೇಕು",
    report_button: "ತುರ್ತು ವರದಿ ಮಾಡಿ",
    safe_zones_button: "ಸುರಕ್ಷಿತ ವಲಯ ಹುಡುಕಿ",
    onboarding_step1_title: "ಹಂತ 1 - ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    onboarding_step2_title: "ಹಂತ 2 - ವೈದ್ಯಕೀಯ ವಿವರಗಳು",
    onboarding_step3_title: "ಹಂತ 3 - ತುರ್ತು ಸಂಪರ್ಕ",
    full_name_label: "ಪೂರ್ಣ ಹೆಸರು",
    age_label: "ವಯಸ್ಸು",
    blood_group_label: "ರಕ್ತದ ಗುಂಪು",
    allergies_label: "ಅಲರ್ಜಿಗಳು",
    medical_conditions_label: "ಪ್ರಸ್ತುತ ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿ",
    medications_label: "ಪ್ರಸ್ತುತ ಔಷಧಗಳು",
    contact_name_label: "ಸಂಪರ್ಕದ ಹೆಸರು",
    relationship_label: "ಸಂಬಂಧ",
    phone_label: "ಫೋನ್ ಸಂಖ್ಯೆ",
    preferred_language_label: "ಆದ್ಯತೆಯ ಭಾಷೆ",
    sos_modal_title: "SOS ಕಳುಹಿಸಬೇಕೆ?",
    sos_category_medical: "ವೈದ್ಯಕೀಯ ತುರ್ತುಸ್ಥಿತಿ",
    sos_category_trapped: "ಸಿಲುಕಿಕೊಂಡಿದ್ದೇನೆ",
    sos_category_fire: "ಬೆಂಕಿ ಅನಾಹುತ",
    sos_category_injury: "ತೀವ್ರ ಗಾಯ",
    sos_category_other: "ಇತರ ತುರ್ತುಸ್ಥಿತಿ",
    sos_sending: "SOS ರವಾನೆಯಾಗುತ್ತಿದೆ...",
    sos_sent_title: "SOS ಕಳುಹಿಸಲಾಗಿದೆ",
    sos_sent_desc: "ನಿಮ್ಮ ತುರ್ತು ವಿನಂತಿಯನ್ನು ರಕ್ಷಣಾ ತಂಡಕ್ಕೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
    logout_confirm_title: "ಲಾಗ್‌ಔಟ್ ಮಾಡಿ ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಬೇಕೆ?",
    logout_confirm_desc: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅಳಿಸಿಹೋಗುತ್ತದೆ.",
    btn_confirm: "ಹೌದು, ರಿಸೆಟ್ ಮಾಡಿ",
    btn_cancel: "ರದ್ದುಮಾಡಿ",
    btn_next: "ಮುಂದೆ",
    btn_complete: "ಪೂರ್ಣಗೊಳಿಸಿ"
  }
};

module.exports = localizedPhrases;
