"""
Configuration settings for ResQMesh backend.
Contains correlation thresholds and classification matrices.
"""

# Spatial correlation threshold in kilometers (0.5 km = 500 meters)
CORRELATION_MAX_DISTANCE_KM = 0.5

# Temporal correlation threshold in minutes
CORRELATION_MAX_TIME_DELTA_MINUTES = 60.0

# Base event types
EVENT_TYPE_PERSON_DETECTED = "PERSON_DETECTED"
EVENT_TYPE_FIRE_DETECTED = "FIRE_DETECTED"
EVENT_TYPE_SMOKE_DETECTED = "SMOKE_DETECTED"
EVENT_TYPE_TRAPPED_PERSON = "TRAPPED_PERSON"
EVENT_TYPE_BLOCKED_ROAD = "BLOCKED_ROAD"
EVENT_TYPE_COLLAPSED_STRUCTURE = "COLLAPSED_STRUCTURE"
EVENT_TYPE_FLOOD = "FLOOD"
EVENT_TYPE_SOS = "SOS"
EVENT_TYPE_MANUAL_REPORT = "MANUAL_REPORT"

# Event type compatibility mapping for incident fusion.
# Events with compatible types in spatial/temporal proximity fuse into one incident.
COMPATIBLE_EVENT_TYPES = {
    EVENT_TYPE_PERSON_DETECTED: {
        EVENT_TYPE_PERSON_DETECTED,
        EVENT_TYPE_TRAPPED_PERSON,
        EVENT_TYPE_FLOOD,
        EVENT_TYPE_SOS,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_TRAPPED_PERSON: {
        EVENT_TYPE_TRAPPED_PERSON,
        EVENT_TYPE_PERSON_DETECTED,
        EVENT_TYPE_SOS,
        EVENT_TYPE_COLLAPSED_STRUCTURE,
        EVENT_TYPE_FIRE_DETECTED,
        EVENT_TYPE_FLOOD,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_SOS: {
        EVENT_TYPE_SOS,
        EVENT_TYPE_PERSON_DETECTED,
        EVENT_TYPE_TRAPPED_PERSON,
        EVENT_TYPE_COLLAPSED_STRUCTURE,
        EVENT_TYPE_FLOOD,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_FIRE_DETECTED: {
        EVENT_TYPE_FIRE_DETECTED,
        EVENT_TYPE_SMOKE_DETECTED,
        EVENT_TYPE_TRAPPED_PERSON,
        EVENT_TYPE_COLLAPSED_STRUCTURE,
        EVENT_TYPE_FLOOD,
        EVENT_TYPE_SOS,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_SMOKE_DETECTED: {
        EVENT_TYPE_SMOKE_DETECTED,
        EVENT_TYPE_FIRE_DETECTED,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_COLLAPSED_STRUCTURE: {
        EVENT_TYPE_COLLAPSED_STRUCTURE,
        EVENT_TYPE_TRAPPED_PERSON,
        EVENT_TYPE_FLOOD,
        EVENT_TYPE_SOS,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_FLOOD: {
        EVENT_TYPE_FLOOD,
        EVENT_TYPE_PERSON_DETECTED,
        EVENT_TYPE_TRAPPED_PERSON,
        EVENT_TYPE_COLLAPSED_STRUCTURE,
        EVENT_TYPE_SOS,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_BLOCKED_ROAD: {
        EVENT_TYPE_BLOCKED_ROAD,
        EVENT_TYPE_MANUAL_REPORT,
    },
    EVENT_TYPE_MANUAL_REPORT: {
        EVENT_TYPE_PERSON_DETECTED,
        EVENT_TYPE_FIRE_DETECTED,
        EVENT_TYPE_SMOKE_DETECTED,
        EVENT_TYPE_TRAPPED_PERSON,
        EVENT_TYPE_COLLAPSED_STRUCTURE,
        EVENT_TYPE_FLOOD,
        EVENT_TYPE_BLOCKED_ROAD,
        EVENT_TYPE_SOS,
        EVENT_TYPE_MANUAL_REPORT,
    },
}
