export default {
  // Navigation
  home: 'होम',
  sos: 'SOS',
  profile: 'प्रोफ़ाइल',

  // Status
  internet: 'इंटरनेट',
  offline: 'ऑफ़लाइन',
  localEmergencyNetwork: 'स्थानीय आपातकालीन नेटवर्क',
  connected: 'जुड़ा हुआ है',

  // Home
  greeting: 'सुप्रभात',
  protectingLocally: 'ResQMesh आपकी स्थानीय रूप से रक्षा कर रहा है',
  nearbySituation: 'आसपास की स्थिति',
  emergencyNearby: 'आसपास आपातकाल',
  emergencyNearbyDesc: '1.8 किमी दूर संरचनात्मक क्षति की सूचना • ब्लॉक ए',
  emergencyNearbyAction: 'निकटतम सुरक्षित क्षेत्र में जाएं।',
  verifiedAdvisory: 'आधिकारिक सलाह',
  highPriority: 'उच्च प्राथमिकता',
  mediumPriority: 'मध्यम प्राथमिकता',
  lowPriority: 'कम प्राथमिकता',
  verified: 'सत्यापित',
  quickActions: 'त्वरित कार्रवाई',
  reportEmergency: 'आपातकाल की रिपोर्ट करें',
  findSafeZone: 'सुरक्षित क्षेत्र खोजें',
  mySafety: 'मेरी सुरक्षा',
  location: 'स्थान',
  battery: 'बैटरी',
  sosStatus: 'SOS स्थिति',
  nearestSafeZone: 'निकटतम सुरक्षित क्षेत्र',

  // SOS
  activateSos: 'SOS सक्रिय करें?',
  sosWarning: 'यह स्थानीय आपातकालीन नेटवर्क के माध्यम से आपके आपातकालीन अनुरोध को प्रसारित करेगा।',
  cancel: 'रद्द करें',
  activate: 'SOS सक्रिय करें',
  sosActive: 'SOS सक्रिय',
  relaying: 'आपका आपातकालीन अनुरोध प्रसारित किया जा रहा है।',
  cancelSos: 'SOS रद्द करें',
  received: 'प्राप्त हुआ',
  searching: 'खोज रहा है',
  voiceCaptured: 'आवाज़ रिकॉर्ड हुई',
  emergencyMessageCreated: 'आपातकालीन संकेत तैयार',
  broadcastingLocally: 'स्थानीय रूप से प्रसारित किया जा रहा है...',
  networkConnected: 'स्थानीय नेटवर्क से जुड़ा हुआ है',
  respondersAlerted: 'राहत दल को सतर्क किया गया',

  // Report Emergency
  reportEmergencyTitle: 'आपातकाल की रिपोर्ट करें',
  categories: 'श्रेणियां',
  fire: 'आग',
  flood: 'बाढ़',
  earthquake: 'भूकंप',
  structuralCollapse: 'संरचनात्मक पतन',
  accident: 'दुर्घटना',
  landslide: 'भूस्खलन',
  other: 'अन्य',
  description: 'विवरण',
  evidence: 'प्रमाण',
  photoAttached: 'फोटो संलग्न ✓',
  remove: 'हटाएं',
  submit: 'रिपोर्ट सबमिट करें',
  reportSent: 'रिपोर्ट भेजी गई ✓',
  reportSentDesc: 'आपकी आपातकालीन रिपोर्ट स्थानीय नेटवर्क के माध्यम से प्रसारित की गई है।',
  creatingIncident: 'घटना बनाई जा रही है...',
  classifyingEmergency: 'आपातकाल वर्गीकृत किया जा रहा है...',
  packagingEvidence: 'सबूत पैक किए जा रहे हैं...',

  // Safe Zones
  offlineDirections: 'ऑफ़लाइन दिशा-निर्देश उपलब्ध',
  capacity: 'क्षमता',

  // Profile
  personalInfo: 'व्यक्तिगत जानकारी',
  medicalDetails: 'चिकित्सा विवरण',
  emergencyContact: 'आपातकालीन संपर्क',
  preferredLanguage: 'पसंदीदा भाषा',
  logoutAndReset: 'लॉग आउट और फिर से शुरू करें',
  logoutAndResetDesc: 'अपनी वर्तमान प्रोफ़ाइल साफ़ करें और सेटअप प्रक्रिया पर वापस जाएं।',
  logoutConfirmTitle: 'फिर से शुरू करें?',
  logoutConfirmMessage: 'क्या आप वाकई लॉग आउट करके फिर से शुरू करना चाहते हैं?\nआपकी वर्तमान प्रोफ़ाइल जानकारी हटा दी जाएगी और आप प्रारंभिक सेटअप पर वापस लौट जाएंगे।',
  logoutConfirmButton: 'हां, लॉग आउट और फिर से शुरू करें',

  // Onboarding
  step1: '3 में से 1 कदम',
  step2: '3 में से 2 कदम',
  step3: '3 में से 3 कदम',
  fullName: 'पूरा नाम',
  age: 'आयु',
  bloodType: 'रक्त प्रकार',
  allergies: 'एलर्जी',
  medicalConditions: 'चिकित्सा शर्तें',
  medications: 'दवाएं',
  contactName: 'संपर्क नाम',
  relationship: 'रिश्ता',
  phoneNumber: 'फ़ोन नंबर',
  enterResqmesh: 'ResQMesh में प्रवेश करें',
  next: 'अगला',
  selectPhoto: 'प्रोफ़ाइल फ़ोटो चुनें',
};
