export default {
  // Navigation
  home: 'HOME',
  alerts: 'ALERTS',
  sos: 'SOS',
  network: 'NETWORK',
  profile: 'PROFILE',

  // Status
  internet: 'INTERNET',
  offline: 'Offline',
  localEmergencyNetwork: 'LOCAL EMERGENCY NETWORK',
  connected: 'Connected',

  // Home
  greeting: 'Good morning',
  protectingLocally: 'ResQMesh is protecting you locally',
  nearbySituation: 'NEARBY SITUATION',
  highPriority: 'HIGH PRIORITY',
  mediumPriority: 'MEDIUM PRIORITY',
  lowPriority: 'LOW PRIORITY',
  verified: 'Verified',
  quickActions: 'QUICK ACTIONS',
  reportEmergency: 'Report Emergency',
  findSafeZone: 'Find Safe Zone',
  mySafety: 'MY SAFETY',
  location: 'Location',
  battery: 'Battery',
  sosStatus: 'SOS Status',
  nearestSafeZone: 'Nearest Safe Zone',

  // SOS
  activateSos: 'Activate SOS?',
  sosWarning: 'This will broadcast your emergency request through the local emergency network.',
  cancel: 'Cancel',
  activate: 'Activate SOS',
  sosActive: 'SOS ACTIVE',
  relaying: 'Your emergency request is being relayed.',
  cancelSos: 'Cancel SOS',
  received: 'Received',
  searching: 'Searching',

  // Report Emergency
  reportEmergencyTitle: 'Report Emergency',
  categories: 'Categories',
  fire: 'Fire',
  flood: 'Flood',
  earthquake: 'Earthquake',
  structuralCollapse: 'Structural Collapse',
  accident: 'Accident',
  landslide: 'Landslide',
  other: 'Other',
  description: 'Description',
  evidence: 'EVIDENCE',
  photoAttached: 'Photo attached ✓',
  remove: 'Remove',
  submit: 'Submit Report',
  reportSent: 'REPORT SENT ✓',
  reportSentDesc: 'Your emergency report has been broadcast through the local network.',
  creatingIncident: 'Creating incident...',
  classifyingEmergency: 'Classifying emergency...',
  packagingEvidence: 'Packaging evidence...',
  broadcastingLocally: 'Broadcasting locally...',

  // Network
  howResqmeshWorks: 'HOW RESQMESH WORKS',
  yourDevice: 'YOUR DEVICE',
  nearbyNode: 'NEARBY NODE',
  relayNode: 'RELAY NODE',
  responder: 'RESPONDER',
  nearbyNodes: 'NEARBY NODES',
  signal: 'Signal',
  role: 'Role',
  messageRelay: 'MESSAGE RELAY',
  hops: 'hops',
  confidence: 'confidence',

  // Safe Zones
  offlineDirections: 'Offline directions available',
  capacity: 'Capacity',

  // Profile
  personalInfo: 'Personal Information',
  medicalDetails: 'Medical Details',
  emergencyContact: 'Emergency Contact',
  preferredLanguage: 'Preferred Language',

  // Onboarding
  step1: 'Step 1 of 3',
  step2: 'Step 2 of 3',
  step3: 'Step 3 of 3',
  fullName: 'Full Name',
  age: 'Age',
  bloodType: 'Blood Type',
  allergies: 'Allergies',
  medicalConditions: 'Medical Conditions',
  medications: 'Medications',
  contactName: 'Contact Name',
  relationship: 'Relationship',
  phoneNumber: 'Phone Number',
  enterResqmesh: 'ENTER ResQMesh',
  next: 'Next',
  selectPhoto: 'Select Profile Photo',
};
